In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('../Datasets/orders.csv')
time = pd.read_csv('../Datasets/messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [9]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [11]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
999 2019-10-15        6371        7      22       2019
30  2019-07-24        2820       16       4       2019
206 2019-04-24        6082        9       1       2019
598 2018-09-07        1134       13      19       2018
470 2019-11-22        3125        1      69       2019

## 2. Extract Month

In [13]:
date['date_month_no'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
927 2018-12-04         219        3       3       2018             12
382 2018-09-30        1935        2      48       2018              9
954 2019-06-21        7350       16      31       2019              6
502 2019-06-19        1232       14       8       2019              6
747 2018-08-06        2490        7       9       2018              8

In [15]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

## 3. Extract Day

In [16]:
date['date_day'] = date['date'].dt.day

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
215,2018-11-01,7266,19,4,2018,11,November,1
965,2019-05-13,1980,6,1,2019,5,May,13
611,2019-01-30,1284,17,11,2019,1,January,30
461,2019-10-20,5125,3,3,2019,10,October,20
902,2019-03-24,5031,0,6,2019,3,March,24

## 4. Extract day of a week

In [18]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [19]:
date['date_dow_name'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [21]:
# Is weekend?
date['date_is_weekend'] = np.where(
    date['date_dow_name'].isin(['Sunday', 'Saturday']),
    1,
    0
)

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

## Extract week of the year

In [24]:
date['date_week'] = date['date'].dt.isocalendar().week

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

## Extract Quarter

In [25]:
date['quarter'] = date['date'].dt.quarter

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

## Extract Semester

In [26]:
date['semester'] = np.where(
    date['quarter'].isin([1, 2]),
    1,
    2
)

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [27]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 20, 0, 45, 11, 912368)

In [28]:
today - date['date']

0     2384 days 00:45:11.912368
1     2866 days 00:45:11.912368
2     2797 days 00:45:11.912368
3     2499 days 00:45:11.912368
4     2722 days 00:45:11.912368
                 ...
995   2812 days 00:45:11.912368
996   2753 days 00:45:11.912368
997   2601 days 00:45:11.912368
998   2666 days 00:45:11.912368
999   2440 days 00:45:11.912368
Name: date, Length: 1000, dtype: timedelta64[ns]

In [29]:
(today - date['date']).dt.days

0      2384
1      2866
2      2797
3      2499
4      2722
       ...
995    2812
996    2753
997    2601
998    2666
999    2440
Name: date, Length: 1000, dtype: int64

In [30]:
# Months passed
np.round((today - date['date'])/np.timedelta64(1, 'M'), 0)

0      77.0
1      92.0
2      90.0
3      81.0
4      88.0
       ...
995    91.0
996    89.0
997    84.0
998    86.0
999    79.0
Name: date, Length: 1000, dtype: float64

In [31]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [32]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [33]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [35]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Time Difference

In [36]:
today - time['date']

0     4569 days 23:55:11.912368
1     4434 days 01:05:11.912368
2     4920 days 00:24:11.912368
3     4222 days 00:14:11.912368
4     4619 days 01:34:11.912368
                 ...
995   5208 days 23:55:11.912368
996   4530 days 01:31:11.912368
997   4995 days 01:08:11.912368
998   5111 days 01:11:11.912368
999   4383 days 01:20:11.912368
Name: date, Length: 1000, dtype: timedelta64[ns]

In [39]:
(today - time['date'])/np.timedelta64(1, 's')

0      3.948477e+08
1      3.831015e+08
2      4.250895e+08
3      3.647817e+08
4      3.990873e+08
           ...
995    4.500573e+08
996    3.913975e+08
997    4.315721e+08
998    4.415947e+08
999    3.786960e+08
Name: date, Length: 1000, dtype: float64

In [41]:
(today - time['date'])/np.timedelta64(1, 'm')

0      6.580795e+06
1      6.385025e+06
2      7.084824e+06
3      6.079694e+06
4      6.651454e+06
           ...
995    7.500955e+06
996    6.523291e+06
997    7.192868e+06
998    7.359911e+06
999    6.311600e+06
Name: date, Length: 1000, dtype: float64

In [40]:
(today - time['date'])/np.timedelta64(1, 'h')

0      109679.919976
1      106417.086642
2      118080.403309
3      101328.236642
4      110857.569976
           ...
995    125015.919976
996    108721.519976
997    119881.136642
998    122665.186642
999    105193.336642
Name: date, Length: 1000, dtype: float64